# Hibernate auto-creates and drops tables on every restart no need for Flyway
spring.jpa.hibernate.ddl-auto=create-drop

# Flyway is disabled in dev schema is managed by Hibernate
spring.flyway.enabled=false

# Show and format SQL queries in console for easier debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator show full health details locally
management.endpoint.health.show-details=always

# Swagger enabled in dev
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
